version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '08:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'angular-eslint'
          - 'zone.js'
      nestjs:
        patterns:
          - '@nestjs/*'
      nx:
        patterns:
          - '@nx/*'
          - '@swc/*'
          - '@swc-node/*'
          - 'nx'
      prisma:
        patterns:
          - '@prisma/*'
          - 'prisma'
      keycloak:
        patterns:
          - '*keycloak*'
      linting:
        patterns:
          - '@ianvs/prettier-plugin-sort-imports'
          - '@typescript-eslint/*'
          - '*eslint*'
          - 'prettier*'
      testing:
        patterns:
          - '@playwright/*'
          - '*jest*'
      babel:
        patterns:
          - '@babel/*'
      types:
        patterns:
          - '@types/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/libs/blockchain/smart-contract'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '08:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    groups:
      hardhat:
        patterns:
          - '@nomicfoundation/*'
          - 'ethers'
          - 'hardhat'
      testing:
        patterns:
          - '@types/chai'
          - '@types/chai-as-promised'
          - '@types/mocha'
          - 'chai'
          - 'mocha'
      typescript:
        patterns:
          - '@types/node'
          - 'typescript'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'
    labels:
      - 'dependencies'
      - 'github-actions'
