services:
  ############
  # DATABASE #
  ############

  postgres:
    image: postgres:17.7-alpine3.23
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=blockchain
      - POSTGRES_DB=h2_trust
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'

  ###########
  # STORAGE #
  ###########

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=blockchain
    ports:
      - '9000:9000'
      - '9090:9090'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - server
      - /data
      - --address=:9000
      - --console-address=:9090

  minio-setup:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mc alias set local http://minio:9000 admin blockchain
        mc mb --ignore-existing local/h2-trust
        mc anonymous set download local/h2-trust

  ##############
  # BLOCKCHAIN #
  ##############

  blockchain:
    build:
      context: ./docker/blockchain
      dockerfile: Dockerfile
    depends_on:
      minio-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - '8545:8545'

  blockchain-setup:
    build:
      context: .
      dockerfile: docker/blockchain-setup/Dockerfile
    depends_on:
      blockchain:
        condition: service_started
    environment:
      NETWORK_URL: 'http://blockchain:8545'

  #########
  # UTILS #
  #########

  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_LOGS: '-error'

networks:
  default:
    name: h2-trust
    driver: bridge
