batch-svc:run-tests:
  needs: []
  stage: test
  extends: .default
  script:
    - npx nx run batch-svc:test
  artifacts:
    paths:
      - ./apps/batch-svc/coverage
    expire_in: 1 week
  allow_failure: true
  only:
    - merge_requests
    - main

batch-svc:sonarqube-check-mr:
  needs:
    - batch-svc:run-tests
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:11.4
    entrypoint: ['']
  variables:
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    # prettier-ignore
    - >
      sonar-scanner
      -Dsonar.projectBaseDir=./apps/batch-svc/
      -Dsonar.pullrequest.key=${CI_MERGE_REQUEST_IID}
      -Dsonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
      -Dsonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  allow_failure: true
  only:
    - merge_requests

batch-svc:sonarqube-check-main:
  needs:
    - batch-svc:run-tests
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:11.4
    entrypoint: ['']
  variables:
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - sonar-scanner -Dsonar.projectBaseDir=./apps/batch-svc/
  allow_failure: true
  only:
    - main

batch-svc:build:
  stage: build
  extends: .default
  script:
    - npx nx run batch-svc:build
  artifacts:
    paths:
      - dist/apps/batch-svc
  only:
    - merge_requests
    - tags

batch-svc:archive:
  needs:
    - batch-svc:build
  stage: archive
  image: docker
  services:
    - docker:dind
  before_script:
    - echo "$HARBOR_TOKEN" | docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull --cache-from ${CRI_PATH}/batch-svc --build-arg APP=batch-svc -t
      ${CRI_PATH}/batch-svc:$CI_COMMIT_TAG -f docker/nest.dockerfile  .
    - docker push ${CRI_PATH}/batch-svc:$CI_COMMIT_TAG
  only:
    - tags
